### ISSUE TITLE
After upgrade to 2.2 on android Pedometer stopped counting steps

### ISSUE THREAD

**Issue by msq-ie** [SecUSo/privacy-friendly-pedometer#79] opened 2021-07-06 11:47 UTC
After upgrade to v2.2 on Android application stopped counting steps.

Samsung Note9 SM-N930F, official ROM, without root

![git01](https://user-images.githubusercontent.com/3123428/124594850-d27b2300-de4f-11eb-9dbd-88ae89bc2879.png)
![git02](https://user-images.githubusercontent.com/3123428/124594865-d60eaa00-de4f-11eb-8e41-00062ae9b6da.png)

**Comment by sleep-yearning** [comment] 2021-07-08 10:08
Thanks for reporting this! Is this a constant problem, i.e. since the upgrade you were not able to count any steps? Or is it situational? 
Have you tried flipping some settings? 
The new version has a step counting threshold, which has to be reached to start counting. 
Also there is compatibility with hardware step counters, does your phone offer such functionality?

**Comment by fibsifan** [comment] 2021-07-08 12:32
I too am experiencing this problem. No steps are counted whatsoever since the latest update.

I was unable to find the mentioned setting for three threshold to begin counting but I went on a small hike yesterday which should be way above any reasonable default value for that threshold ;-)

Reinstalling the app was also without success.

**Comment by fibsifan** [comment] 2021-07-08 12:38
After installing version 1.0.5 from F-Droid, it immediately started working again, so this definitely looks like a regression to me.

**Comment by sleep-yearning** [comment] 2021-07-08 13:39
We are working on a fix.

**Comment by msq-ie** [comment] 2021-07-08 14:30
> Thanks for reporting this! Is this a constant problem, i.e. since the upgrade you were not able to count any steps? Or is it situational?
> Have you tried flipping some settings?

I tried various stuff and setting changes the whole afternoon, including cache clean up. No changes - counter was still showing zero.
There was also an issue with notifications - I set them all to OFF, but every time I opened the app from widget - notification showed up again with alert.

Additionally - clicking 'Correct the steps' closed whole application.

> The new version has a step counting threshold, which has to be reached to start counting.

It was zero for the whole day. I'm sure I've hit the threshold, unless is above 5 000 :)

> Also there is compatibility with hardware step counters, does your phone offer such functionality?

Not sure. Used previous version for two months and everything worked as expected.

Finally rolled back to 1.0.5 and it all works again.

**Comment by sleep-yearning** [comment] 2021-07-09 13:41
The new release should have fixed the issue with old Service API and new release target. If this doesn't fix the issue, we have to look somewhere else. The counting worked on our test devices though.

**Comment by msq-ie** [comment] 2021-07-10 07:13
> 
> 
> The new release should have fixed the issue with old Service API and new release target. If this doesn't fix the issue, we have to look somewhere else. The counting worked on our test devices though.

Unfortunately it doesn't work, at least for me. It should be already a few hundred on the counter but it's zero.


![Screenshot_20210710-080529_Pedometer](https://user-images.githubusercontent.com/3123428/125155261-158a0e80-e14e-11eb-84ae-0b0d65a0d754.png)
![Screenshot_20210710-080535_Pedometer](https://user-images.githubusercontent.com/3123428/125155284-3bafae80-e14e-11eb-8f74-56cfb32932c7.png)

**Comment by fibsifan** [comment] 2021-07-10 11:59
> Unfortunately it doesn't work, at least for me. It should be already a few hundred on the counter but it's zero.

No luck here either. I downloaded the source code from github and tried a little debugging. I've noticed, that my Phone seems to support hardware step detection - at least the method `AndroidVersionHelper#supportsStepDetector` returns `true`. But I've seen warnings in the log like:

> W/org.secuso.privacyfriendlyactivitytracker.utils.StepDetectionServiceHelper: Stopping of service failed or it is not running.

I don't know, whether this is working as intended, but the method `HardwareStepDetectorService#onSensorChanged` never seems to be called, which further manifests my suspicion, that somehow the hardware step detection might needs additional care to keep running on some devices. Mine is a Pixel 5 with latest stock rom and no battery optimization I'd know of.

Hope this helps...

**Comment by fibsifan** [comment] 2021-07-10 12:49
I've tried debugging the working version 1.0.5. It was painful to get it to build, but once it did build and launch, the method `HardwareStepDetectorService#onSensorChanged` was called on my device.

I've accidently built the older version against the newer android api 30 (Android 11) and when I did I was unable to launch the app because of a permission problem: `Permission Denial: startForeground [...] requires android.permission.FOREGROUND_SERVICE`

**Comment by UweBonnes** [comment] 2021-07-11 14:07
On a SAMSUNG M31  no step are counted too.

**Comment by UweBonnes** [comment] 2021-07-11 14:26
Additional the pedometer icon has a orange "1? top right. I find no way to remove this alert. It worked before and a reinstall did not help.

**Comment by SentineI** [comment] 2021-07-13 11:30
Has the 2.3 update fixed this?  

I had this problem after updating to 2.2 on a Motorola phone (Android 10), and had to reinstall 1.0.5 to fix it (with ADB trick to avoid loosing my data - so not keen on randomly trying every new update on the off chance it might work).

**Comment by fibsifan** [comment] 2021-07-13 12:56
> Has the 2.3 update fixed this?

For @msq-ie and me it hasn't. So most likely not for you either.

**Comment by UweBonnes** [comment] 2021-07-13 14:47
Reinstall  of V3.3 still shows no steps. I am located at TU Darmstadt, if you want, you can contact me at 23569

**Comment by msq-ie** [comment] 2021-07-13 14:47
> Has the 2.3 update fixed this?

Nope.

**Comment by UweBonnes** [comment] 2021-07-13 17:57
V2.4 works again on my Samsung M31. Thanks!

**Comment by fibsifan** [comment] 2021-07-13 18:55
Works for me too. The hardware mode has to be enabled on my device and then it asks for a permission and starts counting steps again

**Comment by Kamuno** [comment] 2021-07-13 20:32
Thanks for the feedback. I'll close this issue for now. If the problem persists, please don't hesitate to reopen it.  😄

**Closed by Kamuno** 2021-07-13 20:32 UTC
Labels: bug

**Comment by JCDetwiler** [comment] 2021-07-13 23:39
2.4 seems to be counting steps again, but I'm now seeing it undercounting on my OnePlus phone. It only counted 2500 steps altogether today, despite going on a walk that's usually 4000--5000.

**Comment by UweBonnes** [comment] 2021-07-14 11:44
On my Samsung M31, sensivity is very bad. Normal steps are not counted.

**Comment by sleep-yearning** [comment] 2021-07-14 11:47
If you use the hardware counter, the app has no influence on the sensitivity. 
If you use the accelerometer method, you can try different sensitivity settings.

**Comment by UweBonnes** [comment] 2021-07-14 11:54
Okay, I will experiment with the settings. But up to the update beginning of July, things works out of the box...

**Comment by sleep-yearning** [comment] 2021-07-14 11:58
If you have a different behavior now, this is most likely the change from hardware sensor to accelerometer method.
We made hardware sensor non-default now, because it does not work on all devices even if detected as "supported".

**Comment by RufioHugo** [comment] 2021-08-03 18:08
Issue still exists - why does it stay closed?
